name: Deploy Website to Netlify

# This workflow triggers on pushes to the main branch (or whichever branch you want)
on:
  push:
    branches:
      - main  # You can change 'main' to the branch you use for production (e.g., 'master')

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the runner

    steps:
      # Step 1: Check out the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Node.js and cache dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20  # The Node.js version to use
          cache: "npm"  # Cache npm dependencies to speed up builds

      # Step 3: Install Netlify CLI globally
      - name: Install Netlify CLI
        run: npm install netlify-cli@17.10.1 -g

      # Step 4: Install project dependencies (using npm ci for consistent installs)
      - name: Install dependencies
        run: npm ci

      # Step 5: Build the project (you must have a build script in package.json)
      - name: Build project
        run: npm run build

      # Step 6: Deploy to Netlify
      - name: Deploy to Netlify
        id: netlify_deploy
        run: |
          netlify deploy \
            --dir dist \  # The build output directory (update if your project uses another directory like 'build')
            --site ${{ secrets.NETLIFY_SITE_ID }} \  # Netlify Site ID (stored as a GitHub secret)
            --auth ${{ secrets.NETLIFY_AUTH_TOKEN }}  # Netlify AUTH Token (stored as a GitHub secret)
